Gao\C5Bundle\Entity\Attachment:
    type: entity
    table: attachment
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            column: user_id
        name:
            type: string
            nullable: false
            length: 1000
            fixed: false
        url:
            type: string
            nullable: false
            length: 1000
            fixed: false
        referId:
            type: integer
            nullable: true
            unsigned: false
            column: refer_id
        type:
            type: string
            nullable: false
            length: 10
            fixed: true
    lifecycleCallbacks: {  }
