login:
  path: /login
  defaults: { _controller: GaoC5Bundle:Security:login }

login_check:
  path: /login_check

logout:
  pattern: /logout

login_forgot:
  path: /forgot
  defaults: { _controller: GaoC5Bundle:Security:forgot }

attachment_upload:
    path:     /attachment/upload/{folder}
    defaults: { _controller: GaoC5Bundle:Attachment:upload }

attachment_download:
    path:     /attachment/download
    defaults: { _controller: GaoC5Bundle:Attachment:download }

gao_c5:
    resource: "@GaoC5Bundle/Resources/config/routing.yml"
    prefix:   /c5
