security:
    encoders:
      Gao\C5Bundle\Entity\Users:
        id: sha256salted_encoder
      Gao\AdminBundle\Entity\Admin:
        id: admin.sha256salted_encoder
    role_hierarchy:
      ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    providers:
      admin_db_provider:
        entity:
          class: Gao\AdminBundle\Entity\Admin
      chain_provider:
        chain:
          providers: [in_memory, our_db_provider]
      in_memory:
        memory:
          users:
            user: {password: 123, roles: ROLE_USER}
      our_db_provider:
        entity:
          class: Gao\C5Bundle\Entity\Users

    firewalls:
      admin_secured_area:
        pattern: /admin/.*
        provider: admin_db_provider
        form_login:
          login_path: /admin/login
          check_path: /admin/login_check
          success_handler: admin.security.login_success_handler
          csrf_provider: form.csrf_provider
        logout:
          path: /admin/logout
          target: /admin/login
        remember_me:
          key: adminSecretKey
          lifetime: 360000
          path: /admin
        security: true
        anonymous: true
      general_area:
        pattern: /.*
        provider: chain_provider
        form_login:
          login_path: /login
          check_path: /login_check
          success_handler: security_login_success_handler
          csrf_provider: form.csrf_provider
        logout:
          path: /logout
          target: /login
        remember_me:
          key: aSecretKey
          lifetime: 360000
          path: /
        security: true
        anonymous: true


    access_control:
      - { path: /_wdt/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /admin/forgot, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /admin/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /forgot, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /c5/test, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /bundles/gaoc5/js/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /bundles/gaoc5/css/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /bundles/gaoc5/images/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /bundles/gaoc5/fonts/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /bundles/gaoadmin/js/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /bundles/gaoadmin/css/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /bundles/gaoadmin/images/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /bundles/gaoadmin/fonts/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /admin/bank, roles: ROLE_SUPER_ADMIN }
      - { path: /admin/ajax_bank, roles: ROLE_SUPER_ADMIN }
      - { path: /admin/account/list, roles: ROLE_SUPER_ADMIN }
      - { path: /admin/account/ajax_list, roles: ROLE_SUPER_ADMIN }
      - { path: /admin/account/new, roles: ROLE_SUPER_ADMIN }
      - { path: /admin/account/edit, roles: ROLE_SUPER_ADMIN }
      - { path: /admin/.*, roles: ROLE_ADMIN }
      - { path: /.*, roles: ROLE_USER }
      - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      