parameters:
    system_bot_users: [bot1, bot2, bot3, bot4, bot5]
    default_interest_rate: 30#%
    default_pd_amount: 220#don vi 10000VND
    default_tran_base_amount: 70#don vi 10000VND
    pd_gd_state:
        Pending: Pending
        PD_Requested: PD_Requested
        PD_Matched: PD_Matched
        PD_Done: PD_Done
        GD_Requested: GD_Requested
        GD_Matched: GD_Matched
        GD_Done: GD_Done
    pd_status:
        waiting: 0
        sending: 1
        done: 2
    gd_status:
        waiting: 0
        receiving: 1
        done: 2
    transaction_status:
        pending: 0
        approved: 1
    bank_log_status:
        normal: 0
        blocked: 1
    dispute_status:
        waiting: 0
        approved: 1
        unapproved: 2
    email_forgot_message: Chao %, mat khau moi cua ban la [%]. Vui long cap nhat mat khau ngay khi dang nhap lai.