services:
    sha256salted_encoder:
        class: Gao\C5Bundle\Service\Sha256Salted

    #Biz defined
    pd_biz:
        class: Gao\C5Bundle\Biz\PdBiz
        arguments: [@service_container]
    gd_biz:
        class: Gao\C5Bundle\Biz\GdBiz
        arguments: [@service_container]
    #Service defined
    transaction_service:
        class: Gao\C5Bundle\Service\TransactionService
        arguments: [@doctrine.orm.entity_manager, @service_container]
    automation_service:
        class: Gao\C5Bundle\Service\AutomationService
        arguments: [@doctrine.orm.entity_manager, @service_container]
