services:
    sha256salted_encoder:
        class: Gao\C5Bundle\Service\Sha256Salted

    #Biz defined
    pd_biz:
        class: Gao\C5Bundle\Biz\PdBiz
        arguments: [@service_container]
    gd_biz:
        class: Gao\C5Bundle\Biz\GdBiz
        arguments: [@service_container]
    history_biz:
        class: Gao\C5Bundle\Biz\HistoryBiz
        arguments: [@service_container]
    account_biz:
        class: Gao\C5Bundle\Biz\AccountBiz
        arguments: [@service_container]
    dispute_biz:
        class: Gao\C5Bundle\Biz\DisputeBiz
        arguments: [@service_container]

    #Service defined
    transaction_service:
        class: Gao\C5Bundle\Service\TransactionService
        arguments: [@doctrine.orm.entity_manager, @service_container]
    dispute_service:
        class: Gao\C5Bundle\Service\DisputeService
        arguments: [@doctrine.orm.entity_manager, @service_container]
    automation_service:
        class: Gao\C5Bundle\Service\AutomationService
        arguments: [@doctrine.orm.entity_manager, @service_container]
    attachment_service:
        class: Gao\C5Bundle\Service\AttachmentService
        arguments: [@service_container]

    # Paging module.
    paging_paginate_extension:
        class: Gao\C5Bundle\Service\Paging\PaginateExtension
        arguments: [%paging.defaults.template%]
        tags:
            - { name: twig.extension }
    paging_paginator:
        class: Gao\C5Bundle\Service\Paging\Paginator
        calls:
            - [setItemsLimitPerPage, [%paging.defaults.items_limit_per_page%]]
            - [setPagesLimitInRange, [%paging.defaults.pages_limit_in_range%]]
