services:
    admin.security.login_success_handler:
        class:  Gao\AdminBundle\Service\Security\LoginSuccessHandler
        arguments:  [@service_container, @router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    admin.sha256salted_encoder:
        class: Gao\AdminBundle\Service\Sha256Salted

    #================================
    # BIZ DEFINED
    #================================
    admin.account_detail_biz:
        class: Gao\AdminBundle\Biz\Account\DetailBiz
        arguments: [@service_container]
    admin.account_list_biz:
        class: Gao\AdminBundle\Biz\Account\ListBiz
        arguments: [@service_container]
    admin.user_detail_biz:
        class: Gao\AdminBundle\Biz\User\DetailBiz
        arguments: [@service_container]
    admin.user_list_biz:
        class: Gao\AdminBundle\Biz\User\ListBiz
        arguments: [@service_container]

    #================================
    # SERVICES DEFINED
    #================================
    admin_service:
        class: Gao\AdminBundle\Service\AdminService
        arguments: [@doctrine.orm.entity_manager, @service_container]
    admin.user_service:
        class: Gao\AdminBundle\Service\UserService
        arguments: [@doctrine.orm.entity_manager, @service_container]

    #================================
    # Form type
    #================================
    admin_bundle.form_type.user:
        class: Gao\AdminBundle\Form\UserType
        arguments: [@doctrine.orm.entity_manager]
