services:
    admin.security.login_success_handler:
        class:  Gao\AdminBundle\Service\Security\LoginSuccessHandler
        arguments:  [@service_container, @router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    admin.sha256salted_encoder:
        class: Gao\AdminBundle\Service\Sha256Salted
    admin_service:
        class: Gao\AdminBundle\Service\AdminService
        arguments: [@doctrine.orm.entity_manager, @service_container]
